# Generated by Django 4.1.6 on 2023-02-15 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_bike_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
