# Generated by Django 4.1.7 on 2023-02-19 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_bike_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikesale',
            old_name='units',
            new_name='units_sold',
        ),
        migrations.RemoveField(
            model_name='bikesale',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='bikesale',
            name='net_sale',
        ),
        migrations.RemoveField(
            model_name='bikesale',
            name='refund',
        ),
        migrations.AddField(
            model_name='bikesale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Price at which the bike was sold at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikesale',
            name='units_refunded',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_percentage',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='sale',
            name='net_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
