# Generated by Django 4.1.7 on 2023-02-19 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_units_bikesale_units_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikesale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='backend.sale'),
        ),
    ]
