# Generated by Django 4.1.7 on 2023-02-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_bikesale_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikesale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='backend.sale'),
        ),
    ]
