# Generated by Django 4.1.7 on 2023-02-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_bikesale_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='net_sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
